language: node_js
os:
  - linux
dist: focal
node_js:
  - "node"
branches:
  only:
    - master
script: skip
before_install:
  - npm i -g pnpm
install:
  - pnpm i --frozen-lockfile
before_deploy:
  - pnpm build
deploy:
  provider: pages
  skip_cleanup: true
  token: $GITHUB_TOKEN
  keep_history: true
  local_dir: dist/
  fqdn: ntut.club
  strategy: git
  on:
    branch: master
