language: node_js
node_js:
  - "node"
branches:
  only:
    - master
before_deploy:
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: dist/
  strategy: git
  on:
    branch: master
