name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '17'

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.pnpm
          key: ${{ runner.os }}-node-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm i -g pnpm
      - run: pnpm i --frozen-lockfile
      - run: pnpm run build
        env:
          NODE_OPTIONS: --openssl-legacy-provider

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: ./dist
          cname: ntut.club
